// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhLbCGCzZGDmYL-NbFtEyuAKPYgvcjb2c',
    appId: '1:86632052958:web:c59e2ee53052df662e2a4f',
    messagingSenderId: '86632052958',
    projectId: 'hack-prep-1',
    authDomain: 'hack-prep-1.firebaseapp.com',
    storageBucket: 'hack-prep-1.appspot.com',
    measurementId: 'G-SP0KL9KJYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrmxTwr0d2uYqcw8ygsJbLoxOn5iPPCGU',
    appId: '1:86632052958:android:8359aefe785e33fe2e2a4f',
    messagingSenderId: '86632052958',
    projectId: 'hack-prep-1',
    storageBucket: 'hack-prep-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAod1kAX3G5ujaXy6x5EMaJXW_Na_zdNDc',
    appId: '1:86632052958:ios:f691939eb5e4b2572e2a4f',
    messagingSenderId: '86632052958',
    projectId: 'hack-prep-1',
    storageBucket: 'hack-prep-1.appspot.com',
    iosBundleId: 'com.example.loginLogoutEmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAod1kAX3G5ujaXy6x5EMaJXW_Na_zdNDc',
    appId: '1:86632052958:ios:f691939eb5e4b2572e2a4f',
    messagingSenderId: '86632052958',
    projectId: 'hack-prep-1',
    storageBucket: 'hack-prep-1.appspot.com',
    iosBundleId: 'com.example.loginLogoutEmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhLbCGCzZGDmYL-NbFtEyuAKPYgvcjb2c',
    appId: '1:86632052958:web:8fba28302ca63a192e2a4f',
    messagingSenderId: '86632052958',
    projectId: 'hack-prep-1',
    authDomain: 'hack-prep-1.firebaseapp.com',
    storageBucket: 'hack-prep-1.appspot.com',
    measurementId: 'G-30169BE6BV',
  );
}
